// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rkfwxdkqeohjgppizomb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJrZnd4ZGtxZW9oamdwcGl6b21iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwNTYwMjUsImV4cCI6MjA2NjYzMjAyNX0.fmbBFRvWxT_u46WkujxmMyoCtHyw9YKkV8Zs0DFmPBM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});